name: Triggering a workflow
on:
  workflow_dispatch:

jobs:
  trigger-build:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    name: Invoke workflow with inputs
    steps:
      # Uses -> https://github.com/benc-uk/workflow-dispatch/tree/v1
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: plugin-reusable-workflow.yml

      - name: Run cypress tests
        run: |
          cd ..
        env:
          CYPRESS_DELAY_TEST: '1000'

  call-workflow-passing-data:
    # uses -> https://docs.github.com/en/actions/using-workflows/reusing-workflows
    uses: ./.github/workflows/github-reusable-workflow.yml
    secrets: inherit